// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structs} from '../models';
import {database} from '../models';

export function ChooseMinecraftDir():Promise<string>;

export function GetDownloadQueueState():Promise<structs.DownloadQueueState>;

export function GetDownloadStates(arg1:structs.DownloadStatesRequest):Promise<Array<structs.ModDownloadButtonState>>;

export function GetMinecraftDir():Promise<string>;

export function GetMinecraftReleaseVersions():Promise<Array<string>>;

export function GetPinnedModVersion(arg1:string,arg2:string,arg3:string,arg4:string):Promise<database.PinnedMod>;

export function GetSelectedVersion():Promise<structs.VersionInfo>;

export function GetVersions():Promise<Array<structs.VersionInfo>>;

export function ListMatchingProjectVersions(arg1:structs.SearchModResult,arg2:string,arg3:string):Promise<Array<structs.ProjectVersionResult>>;

export function PinModVersion(arg1:structs.ModVersionPinRequest):Promise<database.PinnedMod>;

export function QueueModDownload(arg1:structs.ModDownloadRequest):Promise<structs.ModDownloadResult>;

export function RefreshSelectedVersionMods():Promise<structs.VersionInfo>;

export function RefreshVersions():Promise<Array<structs.VersionInfo>>;

export function SearchMods(arg1:structs.SearchModsRequest):Promise<void>;

export function SelectVersion(arg1:string):Promise<structs.VersionInfo>;

export function ValidateMinecraftDir():Promise<boolean>;
