// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavoriteMod(arg1) {
  return window['go']['main']['App']['AddFavoriteMod'](arg1);
}

export function AnalyzeBatchIncompatibleConflicts(arg1) {
  return window['go']['main']['App']['AnalyzeBatchIncompatibleConflicts'](arg1);
}

export function ApplyLocalModBatchOperation(arg1) {
  return window['go']['main']['App']['ApplyLocalModBatchOperation'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ChooseCacheDir() {
  return window['go']['main']['App']['ChooseCacheDir']();
}

export function ChooseMinecraftDir() {
  return window['go']['main']['App']['ChooseMinecraftDir']();
}

export function ClearOptionalDependencyReminders() {
  return window['go']['main']['App']['ClearOptionalDependencyReminders']();
}

export function CreateFavoriteList(arg1) {
  return window['go']['main']['App']['CreateFavoriteList'](arg1);
}

export function DeleteFavoriteList(arg1) {
  return window['go']['main']['App']['DeleteFavoriteList'](arg1);
}

export function DismissOptionalDependencyReminder(arg1) {
  return window['go']['main']['App']['DismissOptionalDependencyReminder'](arg1);
}

export function GetDownloadQueueState() {
  return window['go']['main']['App']['GetDownloadQueueState']();
}

export function GetDownloadStates(arg1) {
  return window['go']['main']['App']['GetDownloadStates'](arg1);
}

export function GetMinecraftDir() {
  return window['go']['main']['App']['GetMinecraftDir']();
}

export function GetMinecraftReleaseVersions() {
  return window['go']['main']['App']['GetMinecraftReleaseVersions']();
}

export function GetPinnedModVersion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPinnedModVersion'](arg1, arg2, arg3, arg4);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetSelectedVersion() {
  return window['go']['main']['App']['GetSelectedVersion']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function InstallOptionalDependencies(arg1) {
  return window['go']['main']['App']['InstallOptionalDependencies'](arg1);
}

export function ListFavoriteLists() {
  return window['go']['main']['App']['ListFavoriteLists']();
}

export function ListFavoriteMods(arg1) {
  return window['go']['main']['App']['ListFavoriteMods'](arg1);
}

export function ListMatchingProjectVersions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListMatchingProjectVersions'](arg1, arg2, arg3);
}

export function ListPinnedMods() {
  return window['go']['main']['App']['ListPinnedMods']();
}

export function PinModVersion(arg1) {
  return window['go']['main']['App']['PinModVersion'](arg1);
}

export function QueueModDownload(arg1) {
  return window['go']['main']['App']['QueueModDownload'](arg1);
}

export function RefreshSelectedVersionMods() {
  return window['go']['main']['App']['RefreshSelectedVersionMods']();
}

export function RefreshVersions() {
  return window['go']['main']['App']['RefreshVersions']();
}

export function RemoveFavoriteMod(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RemoveFavoriteMod'](arg1, arg2, arg3, arg4, arg5);
}

export function RenameFavoriteList(arg1, arg2) {
  return window['go']['main']['App']['RenameFavoriteList'](arg1, arg2);
}

export function RetryDownload(arg1) {
  return window['go']['main']['App']['RetryDownload'](arg1);
}

export function SaveAnimationSettings(arg1) {
  return window['go']['main']['App']['SaveAnimationSettings'](arg1);
}

export function SaveApiKeys(arg1) {
  return window['go']['main']['App']['SaveApiKeys'](arg1);
}

export function SaveCacheDirPreference(arg1) {
  return window['go']['main']['App']['SaveCacheDirPreference'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function SearchMods(arg1) {
  return window['go']['main']['App']['SearchMods'](arg1);
}

export function SelectVersion(arg1) {
  return window['go']['main']['App']['SelectVersion'](arg1);
}

export function UnpinMod(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UnpinMod'](arg1, arg2, arg3, arg4);
}

export function ValidateMinecraftDir() {
  return window['go']['main']['App']['ValidateMinecraftDir']();
}
