// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {structs} from '../models';
import {main} from '../models';
import {models} from '../models';

export function AddFavoriteMod(arg1:database.FavoriteMod):Promise<database.FavoriteMod>;

export function ApplyLocalModBatchOperation(arg1:structs.LocalModBatchOperationRequest):Promise<structs.VersionInfo>;

export function CancelDownload(arg1:string):Promise<boolean>;

export function ChooseCacheDir():Promise<main.SettingsView>;

export function ChooseMinecraftDir():Promise<string>;

export function CreateFavoriteList(arg1:string):Promise<database.FavoriteList>;

export function DeleteFavoriteList(arg1:string):Promise<boolean>;

export function GetDownloadQueueState():Promise<structs.DownloadQueueState>;

export function GetDownloadStates(arg1:structs.DownloadStatesRequest):Promise<Array<structs.ModDownloadButtonState>>;

export function GetMinecraftDir():Promise<string>;

export function GetMinecraftReleaseVersions():Promise<Array<string>>;

export function GetPinnedModVersion(arg1:string,arg2:string,arg3:string,arg4:string):Promise<database.PinnedMod>;

export function GetPreferences():Promise<main.AppPreferences>;

export function GetSelectedVersion():Promise<structs.VersionInfo>;

export function GetSettings():Promise<main.SettingsView>;

export function GetVersions():Promise<Array<structs.VersionInfo>>;

export function ListFavoriteLists():Promise<Array<database.FavoriteList>>;

export function ListFavoriteMods(arg1:string):Promise<Array<database.FavoriteMod>>;

export function ListMatchingProjectVersions(arg1:models.ModProject,arg2:string,arg3:string):Promise<Array<models.ModVersion>>;

export function ListPinnedMods():Promise<Array<database.PinnedMod>>;

export function PinModVersion(arg1:structs.ModVersionPinRequest):Promise<database.PinnedMod>;

export function QueueModDownload(arg1:structs.ModDownloadRequest):Promise<structs.ModDownloadResult>;

export function RefreshSelectedVersionMods():Promise<structs.VersionInfo>;

export function RefreshVersions():Promise<Array<structs.VersionInfo>>;

export function RemoveFavoriteMod(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<boolean>;

export function RenameFavoriteList(arg1:string,arg2:string):Promise<database.FavoriteList>;

export function RetryDownload(arg1:string):Promise<boolean>;

export function SaveAnimationSettings(arg1:main.SaveAnimationSettingsRequest):Promise<main.SettingsView>;

export function SaveApiKeys(arg1:main.SaveApiKeysRequest):Promise<main.SettingsView>;

export function SaveCacheDirPreference(arg1:string):Promise<main.SettingsView>;

export function SaveTheme(arg1:string):Promise<string>;

export function SaveUnusedDependencyCleanupSettings(arg1:main.SaveUnusedDependencyCleanupSettingsRequest):Promise<main.SettingsView>;

export function ScanUnusedDependencies(arg1:structs.UnusedDependencyScanRequest):Promise<structs.UnusedDependencyScanResult>;

export function SearchMods(arg1:structs.SearchModsRequest):Promise<void>;

export function SelectVersion(arg1:string):Promise<structs.VersionInfo>;

export function UnpinMod(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function ValidateMinecraftDir():Promise<boolean>;
