// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {appcore} from '../models';
import {structs} from '../models';
import {main} from '../models';
import {models} from '../models';

export function AddFavoriteListReference(arg1:string,arg2:string):Promise<storage.FavoriteListRef>;

export function AddFavoriteMod(arg1:storage.FavoriteMod):Promise<storage.FavoriteMod>;

export function AddFavoriteModsToLists(arg1:appcore.FavoriteBulkAddRequest):Promise<appcore.FavoriteBulkOperationResult>;

export function AnalyzeBatchIncompatibleConflicts(arg1:structs.BatchDownloadRequest):Promise<structs.BatchIncompatibleAnalysis>;

export function AnalyzeLocalModDisableImpact(arg1:structs.LocalModDisableImpactRequest):Promise<structs.LocalModDisableImpactResult>;

export function ApplyFavoriteListCrossVersionCopy(arg1:appcore.FavoriteCrossVersionCopyRequest):Promise<appcore.FavoriteCrossVersionCopyApplyResult>;

export function ApplyLocalModBatchOperation(arg1:structs.LocalModBatchOperationRequest):Promise<structs.VersionInfo>;

export function CancelDownload(arg1:string):Promise<boolean>;

export function ChooseCacheDir(arg1:string):Promise<main.SettingsView>;

export function ChooseMinecraftDir(arg1:string):Promise<string>;

export function ClearOptionalDependencyReminders():Promise<boolean>;

export function CopyFavoriteListToList(arg1:appcore.FavoriteListCopyRequest):Promise<appcore.FavoriteBulkOperationResult>;

export function CreateFavoriteList(arg1:string,arg2:string,arg3:string):Promise<storage.FavoriteList>;

export function DeleteFavoriteList(arg1:string):Promise<boolean>;

export function DismissOptionalDependencyReminder(arg1:string):Promise<boolean>;

export function ExportFavoriteListPackwizZip(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ExportFavoritePackwizResult>;

export function GetAppVersion():Promise<string>;

export function GetDownloadQueueState():Promise<structs.DownloadQueueState>;

export function GetDownloadStates(arg1:structs.DownloadStatesRequest):Promise<Array<structs.ModDownloadButtonState>>;

export function GetMinecraftDir():Promise<string>;

export function GetMinecraftReleaseVersions():Promise<Array<string>>;

export function GetPinnedModVersion(arg1:string,arg2:string,arg3:string,arg4:string):Promise<storage.PinnedMod>;

export function GetPreferences():Promise<main.AppPreferences>;

export function GetSelectedVersion():Promise<structs.VersionInfo>;

export function GetSettings():Promise<main.SettingsView>;

export function GetUsageStats():Promise<storage.UsageStats>;

export function GetVersions():Promise<Array<structs.VersionInfo>>;

export function InstallOptionalDependencies(arg1:string):Promise<Array<structs.ModDownloadResult>>;

export function ListFavoriteContents(arg1:string):Promise<storage.FavoriteListContents>;

export function ListFavoriteListRefs(arg1:string):Promise<Array<storage.FavoriteListRef>>;

export function ListFavoriteLists():Promise<Array<storage.FavoriteList>>;

export function ListFavoriteMods(arg1:string):Promise<Array<storage.FavoriteMod>>;

export function ListMatchingProjectVersions(arg1:models.ModProject,arg2:string,arg3:string):Promise<Array<models.ModVersion>>;

export function ListPinnedMods():Promise<Array<storage.PinnedMod>>;

export function LookupProjectBySlug(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.ModProject>;

export function PinModVersion(arg1:structs.ModVersionPinRequest):Promise<storage.PinnedMod>;

export function PreviewFavoriteListCrossVersionCopy(arg1:appcore.FavoriteCrossVersionCopyRequest):Promise<appcore.FavoriteCrossVersionCopyPreview>;

export function QueueModDownload(arg1:structs.ModDownloadRequest):Promise<structs.ModDownloadResult>;

export function RefreshSelectedVersionMods():Promise<structs.VersionInfo>;

export function RefreshVersions():Promise<Array<structs.VersionInfo>>;

export function RemoveFavoriteListReference(arg1:string,arg2:string):Promise<boolean>;

export function RemoveFavoriteMod(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<boolean>;

export function RenameFavoriteList(arg1:string,arg2:string):Promise<storage.FavoriteList>;

export function ReorderFavoriteLists(arg1:Array<string>):Promise<boolean>;

export function RestoreCachedDependency(arg1:structs.RestoreCachedDependencyRequest):Promise<structs.ModDownloadResult>;

export function RetryDownload(arg1:string):Promise<boolean>;

export function SaveAnimationSettings(arg1:main.SaveAnimationSettingsRequest):Promise<main.SettingsView>;

export function SaveApiKeys(arg1:main.SaveApiKeysRequest):Promise<main.SettingsView>;

export function SaveCacheDirPreference(arg1:string):Promise<main.SettingsView>;

export function SaveLanguage(arg1:string):Promise<string>;

export function SaveMCIMSettings(arg1:main.SaveMCIMSettingsRequest):Promise<main.SettingsView>;

export function SaveNetworkSettings(arg1:main.SaveNetworkSettingsRequest):Promise<main.SettingsView>;

export function SaveSimpleModeSettings(arg1:main.SaveSimpleModeSettingsRequest):Promise<main.SettingsView>;

export function SaveTheme(arg1:string):Promise<string>;

export function SaveUnusedDependencyCleanupSettings(arg1:main.SaveUnusedDependencyCleanupSettingsRequest):Promise<main.SettingsView>;

export function ScanUnusedDependencies(arg1:structs.UnusedDependencyScanRequest):Promise<structs.UnusedDependencyScanResult>;

export function SearchMods(arg1:structs.SearchModsRequest):Promise<void>;

export function SelectVersion(arg1:string):Promise<structs.VersionInfo>;

export function ToggleConnectorLoader():Promise<structs.VersionInfo>;

export function UnpinMod(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function UpdateFavoriteListMetadata(arg1:storage.FavoriteList):Promise<storage.FavoriteList>;

export function ValidateMinecraftDir():Promise<boolean>;
