// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyLocalModBatchOperation(arg1) {
  return window['go']['main']['App']['ApplyLocalModBatchOperation'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ChooseMinecraftDir() {
  return window['go']['main']['App']['ChooseMinecraftDir']();
}

export function GetDownloadQueueState() {
  return window['go']['main']['App']['GetDownloadQueueState']();
}

export function GetDownloadStates(arg1) {
  return window['go']['main']['App']['GetDownloadStates'](arg1);
}

export function GetMinecraftDir() {
  return window['go']['main']['App']['GetMinecraftDir']();
}

export function GetMinecraftReleaseVersions() {
  return window['go']['main']['App']['GetMinecraftReleaseVersions']();
}

export function GetPinnedModVersion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPinnedModVersion'](arg1, arg2, arg3, arg4);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetSelectedVersion() {
  return window['go']['main']['App']['GetSelectedVersion']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function ListMatchingProjectVersions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListMatchingProjectVersions'](arg1, arg2, arg3);
}

export function ListPinnedMods() {
  return window['go']['main']['App']['ListPinnedMods']();
}

export function PinModVersion(arg1) {
  return window['go']['main']['App']['PinModVersion'](arg1);
}

export function QueueModDownload(arg1) {
  return window['go']['main']['App']['QueueModDownload'](arg1);
}

export function RefreshSelectedVersionMods() {
  return window['go']['main']['App']['RefreshSelectedVersionMods']();
}

export function RefreshVersions() {
  return window['go']['main']['App']['RefreshVersions']();
}

export function SaveAnimationSettings(arg1) {
  return window['go']['main']['App']['SaveAnimationSettings'](arg1);
}

export function RetryDownload(arg1) {
  return window['go']['main']['App']['RetryDownload'](arg1);
}

export function SaveApiKeys(arg1) {
  return window['go']['main']['App']['SaveApiKeys'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function SearchMods(arg1) {
  return window['go']['main']['App']['SearchMods'](arg1);
}

export function SelectVersion(arg1) {
  return window['go']['main']['App']['SelectVersion'](arg1);
}

export function UnpinMod(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UnpinMod'](arg1, arg2, arg3, arg4);
}

export function ValidateMinecraftDir() {
  return window['go']['main']['App']['ValidateMinecraftDir']();
}
